// 中文城市名称映射到英文/拼音
export const cityNameMapping: Record<string, string> = {
  // 直辖市
  '北京': 'Beijing',
  '上海': 'Shanghai',
  '天津': 'Tianjin',
  '重庆': 'Chongqing',
  
  // 省会城市
  '广州': 'Guangzhou',
  '深圳': 'Shenzhen',
  '成都': 'Chengdu',
  '杭州': 'Hangzhou',
  '武汉': 'Wuhan',
  '西安': 'Xi\'an',
  '南京': 'Nanjing',
  '郑州': 'Zhengzhou',
  '沈阳': 'Shenyang',
  '长沙': 'Changsha',
  '哈尔滨': 'Harbin',
  '济南': 'Jinan',
  '青岛': 'Qingdao',
  '大连': 'Dalian',
  '昆明': 'Kunming',
  '厦门': 'Xiamen',
  '合肥': 'Hefei',
  '南昌': 'Nanchang',
  '石家庄': 'Shijiazhuang',
  '长春': 'Changchun',
  '太原': 'Taiyuan',
  '南宁': 'Nanning',
  '贵阳': 'Guiyang',
  '福州': 'Fuzhou',
  '海口': 'Haikou',
  '兰州': 'Lanzhou',
  '呼和浩特': 'Hohhot',
  '乌鲁木齐': 'Urumqi',
  '银川': 'Yinchuan',
  '西宁': 'Xining',
  '拉萨': 'Lhasa',
  
  // 其他重要城市
  '苏州': 'Suzhou',
  '无锡': 'Wuxi',
  '宁波': 'Ningbo',
  '温州': 'Wenzhou',
  '珠海': 'Zhuhai',
  '东莞': 'Dongguan',
  '佛山': 'Foshan',
  '中山': 'Zhongshan',
  '惠州': 'Huizhou',
  '江门': 'Jiangmen',
  '湛江': 'Zhanjiang',
  '汕头': 'Shantou',
  '潮州': 'Chaozhou',
  '揭阳': 'Jieyang',
  '梅州': 'Meizhou',
  '茂名': 'Maoming',
  '肇庆': 'Zhaoqing',
  '韶关': 'Shaoguan',
  '清远': 'Qingyuan',
  '阳江': 'Yangjiang',
  '河源': 'Heyuan',
  '汕尾': 'Shanwei',
  '云浮': 'Yunfu',
  
  // 江苏
  '南通': 'Nantong',
  '常州': 'Changzhou',
  '徐州': 'Xuzhou',
  '扬州': 'Yangzhou',
  '镇江': 'Zhenjiang',
  '泰州': 'Taizhou',
  '盐城': 'Yancheng',
  '淮安': 'Huai\'an',
  '连云港': 'Lianyungang',
  '宿迁': 'Suqian',
  
  // 浙江
  '嘉兴': 'Jiaxing',
  '湖州': 'Huzhou',
  '绍兴': 'Shaoxing',
  '金华': 'Jinhua',
  '衢州': 'Quzhou',
  '台州': 'Taizhou',
  '丽水': 'Lishui',
  '舟山': 'Zhoushan',
  
  // 山东
  '烟台': 'Yantai',
  '潍坊': 'Weifang',
  '淄博': 'Zibo',
  '威海': 'Weihai',
  '临沂': 'Linyi',
  '济宁': 'Jining',
  '泰安': 'Tai\'an',
  '聊城': 'Liaocheng',
  '德州': 'Dezhou',
  '滨州': 'Binzhou',
  '菏泽': 'Heze',
  '枣庄': 'Zaozhuang',
  '东营': 'Dongying',
  '日照': 'Rizhao',
  '莱芜': 'Laiwu',
  
  // 河南
  '洛阳': 'Luoyang',
  '开封': 'Kaifeng',
  '新乡': 'Xinxiang',
  '焦作': 'Jiaozuo',
  '安阳': 'Anyang',
  '南阳': 'Nanyang',
  '商丘': 'Shangqiu',
  '信阳': 'Xinyang',
  '周口': 'Zhoukou',
  '驻马店': 'Zhumadian',
  '漯河': 'Luohe',
  '平顶山': 'Pingdingshan',
  '鹤壁': 'Hebi',
  '濮阳': 'Puyang',
  '许昌': 'Xuchang',
  '三门峡': 'Sanmenxia',
  
  // 四川
  '绵阳': 'Mianyang',
  '德阳': 'Deyang',
  '南充': 'Nanchong',
  '宜宾': 'Yibin',
  '自贡': 'Zigong',
  '乐山': 'Leshan',
  '泸州': 'Luzhou',
  '达州': 'Dazhou',
  '内江': 'Neijiang',
  '遂宁': 'Suining',
  '攀枝花': 'Panzhihua',
  '眉山': 'Meishan',
  '广安': 'Guang\'an',
  '资阳': 'Ziyang',
  '凉山': 'Liangshan',
  '广元': 'Guangyuan',
  '雅安': 'Ya\'an',
  '巴中': 'Bazhong',
  
  // 湖北
  '襄阳': 'Xiangyang',
  '宜昌': 'Yichang',
  '荆州': 'Jingzhou',
  '黄冈': 'Huanggang',
  '孝感': 'Xiaogan',
  '黄石': 'Huangshi',
  '咸宁': 'Xianning',
  '荆门': 'Jingmen',
  '鄂州': 'Ezhou',
  '随州': 'Suizhou',
  '十堰': 'Shiyan',
  
  // 湖南
  '株洲': 'Zhuzhou',
  '湘潭': 'Xiangtan',
  '衡阳': 'Hengyang',
  '岳阳': 'Yueyang',
  '常德': 'Changde',
  '郴州': 'Chenzhou',
  '永州': 'Yongzhou',
  '邵阳': 'Shaoyang',
  '怀化': 'Huaihua',
  '益阳': 'Yiyang',
  '张家界': 'Zhangjiajie',
  '娄底': 'Loudi',
  
  // 其他省份重要城市
  '保定': 'Baoding',
  '唐山': 'Tangshan',
  '秦皇岛': 'Qinhuangdao',
  '邯郸': 'Handan',
  '邢台': 'Xingtai',
  '包头': 'Baotou',
  '大同': 'Datong',
  '吉林': 'Jilin',
  '鞍山': 'Anshan',
  '抚顺': 'Fushun',
  '本溪': 'Benxi',
  '丹东': 'Dandong',
  '锦州': 'Jinzhou',
  '营口': 'Yingkou',
  '阜新': 'Fuxin',
  '辽阳': 'Liaoyang',
  '盘锦': 'Panjin',
  '铁岭': 'Tieling',
  '朝阳': 'Chaoyang',
  '葫芦岛': 'Huludao',
  
  // 港澳台
  '香港': 'Hong Kong',
  '澳门': 'Macau',
  '台北': 'Taipei',
  '高雄': 'Kaohsiung',
  '台中': 'Taichung',
  '台南': 'Tainan',
  
  // 亚洲主要城市
  '东京': 'Tokyo',
  '大阪': 'Osaka',
  '京都': 'Kyoto',
  '名古屋': 'Nagoya',
  '札幌': 'Sapporo',
  '福冈': 'Fukuoka',
  '首尔': 'Seoul',
  '釜山': 'Busan',
  '仁川': 'Incheon',
  '新加坡': 'Singapore',
  '吉隆坡': 'Kuala Lumpur',
  '曼谷': 'Bangkok',
  '河内': 'Hanoi',
  '胡志明市': 'Ho Chi Minh City',
  '马尼拉': 'Manila',
  '雅加达': 'Jakarta',
  '金边': 'Phnom Penh',
  '万象': 'Vientiane',
  '仰光': 'Yangon',
  '达卡': 'Dhaka',
  '加尔各答': 'Kolkata',
  '孟买': 'Mumbai',
  '新德里': 'New Delhi',
  '班加罗尔': 'Bangalore',
  '海德拉巴': 'Hyderabad',
  '金奈': 'Chennai',
  '伊斯坦布尔': 'Istanbul',
  '安卡拉': 'Ankara',
  '德黑兰': 'Tehran',
  '迪拜': 'Dubai',
  '阿布扎比': 'Abu Dhabi',
  '利雅得': 'Riyadh',
  '吉达': 'Jeddah',
  '耶路撒冷': 'Jerusalem',
  '特拉维夫': 'Tel Aviv',
  '安曼': 'Amman',
  '贝鲁特': 'Beirut',
  '大马士革': 'Damascus',
  '巴格达': 'Baghdad',
  '科威特城': 'Kuwait City',
  
  // 欧洲主要城市
  '伦敦': 'London',
  '曼彻斯特': 'Manchester',
  '利物浦': 'Liverpool',
  '爱丁堡': 'Edinburgh',
  '格拉斯哥': 'Glasgow',
  '巴黎': 'Paris',
  '马赛': 'Marseille',
  '里昂': 'Lyon',
  '尼斯': 'Nice',
  '柏林': 'Berlin',
  '慕尼黑': 'Munich',
  '法兰克福': 'Frankfurt',
  '汉堡': 'Hamburg',
  '科隆': 'Cologne',
  '罗马': 'Rome',
  '米兰': 'Milan',
  '威尼斯': 'Venice',
  '佛罗伦萨': 'Florence',
  '那不勒斯': 'Naples',
  '马德里': 'Madrid',
  '巴塞罗那': 'Barcelona',
  '瓦伦西亚': 'Valencia',
  '塞维利亚': 'Seville',
  '里斯本': 'Lisbon',
  '波尔图': 'Porto',
  '阿姆斯特丹': 'Amsterdam',
  '鹿特丹': 'Rotterdam',
  '布鲁塞尔': 'Brussels',
  '维也纳': 'Vienna',
  '苏黎世': 'Zurich',
  '日内瓦': 'Geneva',
  '斯德哥尔摩': 'Stockholm',
  '哥本哈根': 'Copenhagen',
  '奥斯陆': 'Oslo',
  '赫尔辛基': 'Helsinki',
  '华沙': 'Warsaw',
  '布拉格': 'Prague',
  '布达佩斯': 'Budapest',
  '雅典': 'Athens',
  '莫斯科': 'Moscow',
  '圣彼得堡': 'Saint Petersburg',
  '基辅': 'Kyiv',
  '明斯克': 'Minsk',
  '贝尔格莱德': 'Belgrade',
  '布加勒斯特': 'Bucharest',
  '索非亚': 'Sofia',
  '里加': 'Riga',
  '塔林': 'Tallinn',
  '维尔纽斯': 'Vilnius',
  '都柏林': 'Dublin',
  '雷克雅未克': 'Reykjavik',
  
  // 北美洲主要城市
  '纽约': 'New York',
  '洛杉矶': 'Los Angeles',
  '芝加哥': 'Chicago',
  '休斯顿': 'Houston',
  '凤凰城': 'Phoenix',
  '费城': 'Philadelphia',
  '圣安东尼奥': 'San Antonio',
  '圣迭戈': 'San Diego',
  '达拉斯': 'Dallas',
  '圣何塞': 'San Jose',
  '旧金山': 'San Francisco',
  '西雅图': 'Seattle',
  '波士顿': 'Boston',
  '拉斯维加斯': 'Las Vegas',
  '迈阿密': 'Miami',
  '亚特兰大': 'Atlanta',
  '华盛顿': 'Washington',
  '丹佛': 'Denver',
  '波特兰': 'Portland',
  '奥斯汀': 'Austin',
  '底特律': 'Detroit',
  '明尼阿波利斯': 'Minneapolis',
  '夏洛特': 'Charlotte',
  '新奥尔良': 'New Orleans',
  '盐湖城': 'Salt Lake City',
  '多伦多': 'Toronto',
  '温哥华': 'Vancouver',
  '蒙特利尔': 'Montreal',
  '渥太华': 'Ottawa',
  '卡尔加里': 'Calgary',
  '埃德蒙顿': 'Edmonton',
  '魁北克': 'Quebec City',
  '墨西哥城': 'Mexico City',
  '瓜达拉哈拉': 'Guadalajara',
  '蒙特雷': 'Monterrey',
  '哈瓦那': 'Havana',
  
  // 南美洲主要城市
  '圣保罗': 'Sao Paulo',
  '里约热内卢': 'Rio de Janeiro',
  '巴西利亚': 'Brasilia',
  '布宜诺斯艾利斯': 'Buenos Aires',
  '利马': 'Lima',
  '波哥大': 'Bogota',
  '圣地亚哥': 'Santiago',
  '加拉加斯': 'Caracas',
  '基多': 'Quito',
  '蒙得维的亚': 'Montevideo',
  '亚松森': 'Asuncion',
  '拉巴斯': 'La Paz',
  '乔治敦': 'Georgetown',
  
  // 大洋洲主要城市
  '悉尼': 'Sydney',
  '墨尔本': 'Melbourne',
  '布里斯班': 'Brisbane',
  '珀斯': 'Perth',
  '阿德莱德': 'Adelaide',
  '堪培拉': 'Canberra',
  '奥克兰': 'Auckland',
  '惠灵顿': 'Wellington',
  '基督城': 'Christchurch',
  '苏瓦': 'Suva',
  
  // 非洲主要城市
  '开罗': 'Cairo',
  '亚历山大': 'Alexandria',
  '拉各斯': 'Lagos',
  '约翰内斯堡': 'Johannesburg',
  '开普敦': 'Cape Town',
  '德班': 'Durban',
  '比勒陀利亚': 'Pretoria',
  '内罗毕': 'Nairobi',
  '达累斯萨拉姆': 'Dar es Salaam',
  '卡萨布兰卡': 'Casablanca',
  '阿尔及尔': 'Algiers',
  '突尼斯': 'Tunis',
  '的黎波里': 'Tripoli',
  '金沙萨': 'Kinshasa',
  '阿克拉': 'Accra',
  '阿比让': 'Abidjan',
  '亚的斯亚贝巴': 'Addis Ababa',
  '哈拉雷': 'Harare',
  '卢萨卡': 'Lusaka',
};

/**
 * 将城市名称转换为 API 可识别的格式
 * @param cityName 用户输入的城市名称（可能是中文或英文）
 * @returns API 可识别的英文城市名称
 */
export function convertCityName(cityName: string): string {
  const trimmedName = cityName.trim();
  
  // 如果是中文城市名，尝试转换
  if (cityNameMapping[trimmedName]) {
    return cityNameMapping[trimmedName];
  }
  
  // 如果不在映射表中，直接返回原名称（可能是英文或其他语言）
  return trimmedName;
}

/**
 * 检查是否为中文城市名
 * @param cityName 城市名称
 * @returns 是否为中文
 */
export function isChineseCityName(cityName: string): boolean {
  return /[\u4e00-\u9fa5]/.test(cityName);
}
